		DW	OFFSET	NullMobSctr	;0

		DW	OFFSET MobSctr5_4	;  1
		DW	OFFSET MobSctr11_2	;  2
		DW	OFFSET MobSctr26_4	;  3
		DW	OFFSET MobSctr25_6	;  4
		DW	OFFSET MobSctr11_13	;  5
		DW	OFFSET MobSctr23_10	;  6
		DW	OFFSET MobSctr4_26	;  7
		DW	OFFSET MobSctr5_16	;  8
		DW	OFFSET MobSctr16_16	;  9
		DW	OFFSET MobSctr23_25	; 10
		DW	OFFSET MobSctr1_9	; 11
		DW	OFFSET MobSctr5_8	; 12
		DW	OFFSET MobSctr21_3	; 13
		DW	OFFSET MobSctr28_4	; 14
		DW	OFFSET MobSctr22_17	; 15
		DW	OFFSET MobSctr24_20	; 16
		DW	OFFSET MobSctr23_26	; 17
		DW	OFFSET MobSctr15_28	; 18
		DW	OFFSET MobSctr13_20	; 19
		DW	OFFSET MobSctr8_9	; 20
		DW	OFFSET NullObjList	; 21
		DW	OFFSET NullObjList	; 22
		DW	OFFSET NullObjList	; 23
		DW	OFFSET NullObjList	; 24
		DW	OFFSET NullObjList	; 25
		DW	OFFSET NullObjList	; 26
		DW	OFFSET NullObjList	; 27
		DW	OFFSET NullObjList	; 28
		DW	OFFSET NullObjList	; 29
		DW	OFFSET NullObjList	; 30
		DW	OFFSET NullObjList	; 31
		DW	OFFSET NullObjList	; 32
		DW	OFFSET NullObjList	; 33
		DW	OFFSET NullObjList	; 34
		DW	OFFSET NullObjList	; 35
		DW	OFFSET NullObjList	; 36
		DW	OFFSET NullObjList	; 37
		DW	OFFSET NullObjList	; 38
		DW	OFFSET NullObjList	; 39
		DW	OFFSET NullObjList	; 40
		DW	OFFSET NullObjList	; 41
		DW	OFFSET NullObjList	; 42
		DW	OFFSET NullObjList	; 43
		DW	OFFSET NullObjList	; 44
		DW	OFFSET NullObjList	; 45
		DW	OFFSET NullObjList	; 46
		DW	OFFSET NullObjList	; 47
		DW	OFFSET NullObjList	; 48
		DW	OFFSET NullObjList	; 49
		DW	OFFSET NullObjList	; 50
		DW	OFFSET NullObjList	; 51
		DW	OFFSET NullObjList	; 52
		DW	OFFSET NullObjList	; 53
		DW	OFFSET NullObjList	; 54
		DW	OFFSET NullObjList	; 55
		DW	OFFSET NullObjList	; 56
		DW	OFFSET NullObjList	; 57
		DW	OFFSET NullObjList	; 58
		DW	OFFSET NullObjList	; 59
		DW	OFFSET NullObjList	; 60
		DW	OFFSET NullObjList	; 61
		DW	OFFSET NullObjList	; 62
		DW	OFFSET NullObjList	; 63
		DW	OFFSET NullObjList	; 64
		DW	OFFSET NullObjList	; 65
		DW	OFFSET NullObjList	; 66
		DW	OFFSET NullObjList	; 67
		DW	OFFSET NullObjList	; 68
		DW	OFFSET NullObjList	; 69
		DW	OFFSET NullObjList	; 70
		DW	OFFSET NullObjList	; 71
		DW	OFFSET NullObjList	; 72
		DW	OFFSET NullObjList	; 73
		DW	OFFSET NullObjList	; 74
		DW	OFFSET NullObjList	; 75
		DW	OFFSET NullObjList	; 76
		DW	OFFSET NullObjList	; 77
		DW	OFFSET NullObjList	; 78
		DW	OFFSET NullObjList	; 79
		DW	OFFSET NullObjList	; 80
		DW	OFFSET NullObjList	; 81
		DW	OFFSET NullObjList	; 82
		DW	OFFSET NullObjList	; 83
		DW	OFFSET NullObjList	; 84
		DW	OFFSET NullObjList	; 85
		DW	OFFSET NullObjList	; 86
		DW	OFFSET NullObjList	; 87
		DW	OFFSET NullObjList	; 88
		DW	OFFSET NullObjList	; 89
		DW	OFFSET NullObjList	; 90
		DW	OFFSET NullObjList	; 91
		DW	OFFSET NullObjList	; 92
		DW	OFFSET NullObjList	; 93
		DW	OFFSET NullObjList	; 94
		DW	OFFSET NullObjList	; 95
		DW	OFFSET NullObjList	; 96
		DW	OFFSET NullObjList	; 97
		DW	OFFSET NullObjList	; 98
		DW	OFFSET NullObjList	; 99
		DW	OFFSET NullObjList	;100
		DW	OFFSET NullObjList	;101
		DW	OFFSET NullObjList	;102
		DW	OFFSET NullObjList	;103
		DW	OFFSET NullObjList	;104
		DW	OFFSET NullObjList	;105
		DW	OFFSET NullObjList	;106
		DW	OFFSET NullObjList	;107
		DW	OFFSET NullObjList	;108
		DW	OFFSET NullObjList	;109
		DW	OFFSET NullObjList	;110
		DW	OFFSET NullObjList	;111
		DW	OFFSET NullObjList	;112
		DW	OFFSET NullObjList	;113
		DW	OFFSET NullObjList	;114
		DW	OFFSET NullObjList	;115
		DW	OFFSET NullObjList	;116
		DW	OFFSET NullObjList	;117
		DW	OFFSET NullObjList	;118
		DW	OFFSET NullObjList	;119
		DW	OFFSET NullObjList	;120
		DW	OFFSET NullObjList	;121
		DW	OFFSET NullObjList	;122
		DW	OFFSET NullObjList	;123
		DW	OFFSET NullObjList	;124
		DW	OFFSET NullObjList	;125
		DW	OFFSET NullObjList	;126
		DW	OFFSET NullObjList	;127
		DW	OFFSET NullObjList	;128
		DW	OFFSET NullObjList	;129
		DW	OFFSET NullObjList	;130
		DW	OFFSET NullObjList	;131
		DW	OFFSET NullObjList	;132
		DW	OFFSET NullObjList	;133
		DW	OFFSET NullObjList	;134
		DW	OFFSET NullObjList	;135
		DW	OFFSET NullObjList	;136
		DW	OFFSET NullObjList	;137
		DW	OFFSET NullObjList	;138
		DW	OFFSET NullObjList	;139
		DW	OFFSET NullObjList	;140
		DW	OFFSET NullObjList	;141
		DW	OFFSET NullObjList	;142
		DW	OFFSET NullObjList	;143
		DW	OFFSET NullObjList	;144
		DW	OFFSET NullObjList	;145
		DW	OFFSET NullObjList	;146
		DW	OFFSET NullObjList	;147
		DW	OFFSET NullObjList	;148
		DW	OFFSET NullObjList	;149
		DW	OFFSET NullObjList	;150
		DW	OFFSET NullObjList	;151
		DW	OFFSET NullObjList	;152
		DW	OFFSET NullObjList	;153
		DW	OFFSET NullObjList	;154
		DW	OFFSET NullObjList	;155
		DW	OFFSET NullObjList	;156
		DW	OFFSET NullObjList	;157
		DW	OFFSET NullObjList	;158
		DW	OFFSET NullObjList	;159
		DW	OFFSET NullObjList	;160
		DW	OFFSET NullObjList	;161
		DW	OFFSET NullObjList	;162
		DW	OFFSET NullObjList	;163
		DW	OFFSET NullObjList	;164
		DW	OFFSET NullObjList	;165
		DW	OFFSET NullObjList	;166
		DW	OFFSET NullObjList	;167
		DW	OFFSET NullObjList	;168
		DW	OFFSET NullObjList	;169
		DW	OFFSET NullObjList	;170
		DW	OFFSET NullObjList	;171
		DW	OFFSET NullObjList	;172
		DW	OFFSET NullObjList	;173
		DW	OFFSET NullObjList	;174
		DW	OFFSET NullObjList	;175
		DW	OFFSET NullObjList	;176
		DW	OFFSET NullObjList	;177
		DW	OFFSET NullObjList	;178
		DW	OFFSET NullObjList	;179
		DW	OFFSET NullObjList	;180
		DW	OFFSET NullObjList	;181
		DW	OFFSET NullObjList	;182
		DW	OFFSET NullObjList	;183
		DW	OFFSET NullObjList	;184
		DW	OFFSET NullObjList	;185
		DW	OFFSET NullObjList	;186
		DW	OFFSET NullObjList	;187
		DW	OFFSET NullObjList	;188
		DW	OFFSET NullObjList	;189
		DW	OFFSET NullObjList	;190
		DW	OFFSET NullObjList	;191
		DW	OFFSET NullObjList	;192
		DW	OFFSET NullObjList	;193
		DW	OFFSET NullObjList	;194
		DW	OFFSET NullObjList	;195
		DW	OFFSET NullObjList	;196
		DW	OFFSET NullObjList	;197
		DW	OFFSET NullObjList	;198
		DW	OFFSET NullObjList	;199
		DW	OFFSET NullObjList	;200
		DW	OFFSET NullObjList	;201
		DW	OFFSET NullObjList	;202
		DW	OFFSET NullObjList	;203
		DW	OFFSET NullObjList	;204
		DW	OFFSET NullObjList	;205
		DW	OFFSET NullObjList	;206
		DW	OFFSET NullObjList	;207
		DW	OFFSET NullObjList	;208
		DW	OFFSET NullObjList	;209
		DW	OFFSET NullObjList	;210
		DW	OFFSET NullObjList	;211
		DW	OFFSET NullObjList	;212
		DW	OFFSET NullObjList	;213
		DW	OFFSET NullObjList	;214
		DW	OFFSET NullObjList	;215
		DW	OFFSET NullObjList	;216
		DW	OFFSET NullObjList	;217
		DW	OFFSET NullObjList	;218
		DW	OFFSET NullObjList	;219
		DW	OFFSET NullObjList	;220
		DW	OFFSET NullObjList	;221
		DW	OFFSET NullObjList	;222
		DW	OFFSET NullObjList	;223
		DW	OFFSET NullObjList	;224
		DW	OFFSET NullObjList	;225
		DW	OFFSET NullObjList	;226
		DW	OFFSET NullObjList	;227
		DW	OFFSET NullObjList	;228
		DW	OFFSET NullObjList	;229
		DW	OFFSET NullObjList	;230
		DW	OFFSET NullObjList	;231
		DW	OFFSET NullObjList	;232
		DW	OFFSET NullObjList	;233
		DW	OFFSET NullObjList	;234
		DW	OFFSET NullObjList	;235
		DW	OFFSET NullObjList	;236
		DW	OFFSET NullObjList	;237
		DW	OFFSET NullObjList	;238
		DW	OFFSET NullObjList	;239
		DW	OFFSET NullObjList	;240
		DW	OFFSET NullObjList	;241
		DW	OFFSET NullObjList	;242
		DW	OFFSET NullObjList	;243
		DW	OFFSET NullObjList	;244
		DW	OFFSET NullObjList	;245
		DW	OFFSET NullObjList	;246
		DW	OFFSET NullObjList	;247
		DW	OFFSET NullObjList	;248
		DW	OFFSET NullObjList	;249
		DW	OFFSET NullObjList	;250
		DW	OFFSET NullObjList	;251
		DW	OFFSET NullObjList	;252
		DW	OFFSET NullObjList	;253
		DW	OFFSET NullObjList	;254
		DW	OFFSET NullObjList	;255
