;****************************************************************************
;*
;* PALETTES.INC
;*
;* Logical colour equates.
;*
;* 31.10.1990 - KJB
;*
;****************************************************************************

;--------------------------------------
;* standard EGA colours (do not change)
;--------------------------------------

COL_BLACK	EQU	0
COL_BLUE	EQU	1
COL_GREEN 	EQU	2
COL_CYAN	EQU	3
COL_RED		EQU	4
COL_MAGENTA	EQU	5
COL_BROWN	EQU	6
COL_LT_GREY	EQU	7
COL_DK_GREY	EQU	8
COL_LT_BLUE	EQU	9
COL_LT_GREEN	EQU	10
COL_LT_CYAN	EQU	11
COL_LT_RED	EQU	12
COL_LT_MAGENTA	EQU	13
COL_YELLOW	EQU	14
COL_WHITE	EQU	15

